{% set name = "jsonpointer" %}
{% set version = "2.4" %}
{% set bundle = "tar.gz" %}
{% set hash = "585cee82b70211fa9e6043b7bb89db6e1aa49524340dde8ad6b63206ea689d88" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - jsonpointer

about:
  home: https://github.com/stefankoegl/python-json-pointer
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Identify specific nodes in a JSON document (RFC 6901)
  dev_url: https://github.com/stefankoegl/python-json-pointer
  doc_url: https://python-json-pointer.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
